name: flutter_nuedc_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  opencv_core: ^1.4.3
  camera: ^0.11.2
  path_provider: ^2.1.5
  onnxruntime: ^1.4.1
  get: ^4.7.2
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_cube:
    path: extra/flutter_cube

dependency_overrides:
  camera_android: ^0.10.10+5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/3D/

hooks:
  user_defines:
    dartcv4:
      include_modules:
        - imgcodecs
        - imgproc
        - videoio